# Generated by Django 4.2 on 2023-04-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="school_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Amherst College", "Amherst"),
                    ("Babson College", "Babson"),
                    ("Barnard College", "Barnard"),
                    ("Boston College", "BC"),
                    ("Boston University", "BU"),
                    ("Bowdoin College", "Bowdoin"),
                    ("Brandeis University", "Brandeis"),
                    ("Brown University", "Brown"),
                    ("California Institute of Technology", "Caltech"),
                    ("Carnegie Mellon University", "CMU"),
                    ("Claremont McKenna College", "CMC"),
                    ("Columbia University", "Columbia"),
                    ("Cornell University", "Cornell"),
                    ("Dartmouth College", "Dartmouth"),
                    ("Duke University", "Duke"),
                    ("Emory University", "Emory"),
                    ("Georgetown University", "Georgetown"),
                    ("Georgia Institute of Technology", "Georgia Tech"),
                    ("Harvard University", "Harvard"),
                    ("Harvey Mudd College", "HMC"),
                    ("Johns Hopkins University", "JHU"),
                    ("Massachusetts Institute of Technology", "MIT"),
                    ("Middlebury College", "Middlebury"),
                    ("New York University", "NYU"),
                    ("New York University Tandon School of Engineering", "Tandon"),
                    ("Northwestern University", "Northwestern"),
                    ("Pomona College", "Pomona"),
                    ("Princeton University", "Princeton"),
                    ("Rice University", "Rice"),
                    ("Stanford University", "Stanford"),
                    ("Swarthmore College", "Swarthmore"),
                    ("Tufts University", "Tufts"),
                    ("University of California, Berkeley", "UC Berkeley"),
                    ("University of California, Los Angeles", "UCLA"),
                    ("University of California, San Diego", "UCSD"),
                    ("University of California, Santa Barbara", "UCSB"),
                    ("University of Chicago", "UChicago"),
                    ("University of Michigan, Ann Arbor", "Michigan"),
                    ("University of North Carolina at Chapel Hill", "UNC"),
                    ("University of Notre Dame", "Notre Dame"),
                    ("University of Pennsylvania", "UPenn"),
                    ("University of Southern California", "USC"),
                    ("University of Texas at Austin", "UT Austin"),
                    ("University of Virginia", "UVA"),
                    ("University of Washington", "UW"),
                    ("Vanderbilt University", "Vanderbilt"),
                    ("Washington University in St. Louis", "WashU"),
                    ("Wellesley College", "Wellesley"),
                    ("Williams College", "Williams"),
                    ("Yale University", "Yale"),
                ],
                max_length=100,
            ),
        ),
    ]
