# Generated by Django 4.2 on 2023-04-13 01:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_remove_profile_first_name_remove_profile_last_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill_Set",
            new_name="Skills",
        ),
    ]
