# Generated by Django 4.2 on 2023-04-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_skills_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
    ]
