# Generated by Django 4.2 on 2023-04-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_school_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="school_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Amherst", "Amherst College/Amherst"),
                    ("Babson", "Babson College/Babson"),
                    ("Barnard", "Barnard College/Barnard"),
                    ("BC", "Boston College/BC"),
                    ("BU", "Boston University/BU"),
                    ("Bowdoin", "Bowdoin College/Bowdoin"),
                    ("Brandeis", "Brandeis University/Brandeis"),
                    ("Brown", "Brown University/Brown"),
                    ("Caltech", "California Institute of Technology/Caltech"),
                    ("CMU", "Carnegie Mellon University/CMU"),
                    ("CMC", "Claremont McKenna College/CMC"),
                    ("Columbia", "Columbia University/Columbia"),
                    ("Cornell", "Cornell University/Cornell"),
                    ("Dartmouth", "Dartmouth College/Dartmouth"),
                    ("Duke", "Duke University/Duke"),
                    ("Emory", "Emory University/Emory"),
                    ("Georgetown", "Georgetown University/Georgetown"),
                    ("Georgia Tech", "Georgia Institute of Technology/Georgia Tech"),
                    ("Harvard", "Harvard University/Harvard"),
                    ("HMC", "Harvey Mudd College/HMC"),
                    ("JHU", "Johns Hopkins University/JHU"),
                    ("MIT", "Massachusetts Institute of Technology/MIT"),
                    ("Middlebury", "Middlebury College/Middlebury"),
                    ("NYU", "New York University/NYU"),
                    (
                        "Tandon",
                        "New York University Tandon School of Engineering/Tandon",
                    ),
                    ("Northwestern", "Northwestern University/Northwestern"),
                    ("Pomona", "Pomona College/Pomona"),
                    ("Princeton", "Princeton University/Princeton"),
                    ("Rice", "Rice University/Rice"),
                    ("Stanford", "Stanford University/Stanford"),
                    ("Swarthmore", "Swarthmore College/Swarthmore"),
                    ("Tufts", "Tufts University/Tufts"),
                    ("UC Berkeley", "University of California, Berkeley/UC Berkeley"),
                    ("UCLA", "University of California, Los Angeles/UCLA"),
                    ("UCSD", "University of California, San Diego/UCSD"),
                    ("UCSB", "University of California, Santa Barbara/UCSB"),
                    ("UChicago", "University of Chicago/UChicago"),
                    ("Michigan", "University of Michigan, Ann Arbor/Michigan"),
                    ("UNC", "University of North Carolina at Chapel Hill/UNC"),
                    ("Notre Dame", "University of Notre Dame/Notre Dame"),
                    ("UPenn", "University of Pennsylvania/UPenn"),
                    ("USC", "University of Southern California/USC"),
                    ("UT Austin", "University of Texas at Austin/UT Austin"),
                    ("UVA", "University of Virginia/UVA"),
                    ("UW", "University of Washington/UW"),
                    ("Vanderbilt", "Vanderbilt University/Vanderbilt"),
                    ("WashU", "Washington University in St. Louis/WashU"),
                    ("Wellesley", "Wellesley College/Wellesley"),
                    ("Williams", "Williams College/Williams"),
                    ("Yale", "Yale University/Yale"),
                ],
                max_length=100,
            ),
        ),
    ]
