# Generated by Django 4.2 on 2023-04-17 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_remove_profile_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="skill",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="skill",
            field=models.CharField(
                choices=[
                    ("Skill 1", "C++"),
                    ("Skill 2", "Skill 2"),
                    ("Skill 3", "Skill 3"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("skill", "user")},
        ),
    ]
