# Generated by Django 4.2 on 2023-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profile_school_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="zoom_link",
            field=models.URLField(blank=True),
        ),
    ]
