# Generated by Django 4.2 on 2023-04-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_zoom_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="zoom_link",
            new_name="zoom_meeting_link",
        ),
    ]
