# Generated by Django 4.2 on 2023-04-27 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0008_rename_zoom_link_profile_zoom_meeting_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("interview_date", models.DateField(default=django.utils.timezone.now)),
                ("rating", models.IntegerField(default=0)),
                ("review", models.TextField()),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requesting_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviewee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
