# Generated by Django 4.2 on 2023-04-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_skill_skill_level_alter_profile_gpa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="skill",
            name="skill",
            field=models.CharField(
                choices=[
                    ("C++", "C++"),
                    ("Python", "Python"),
                    ("Java", "Java"),
                    ("JavaScript", "JavaScript"),
                    ("HTML/CSS", "HTML/CSS"),
                    ("Ruby", "Ruby"),
                    ("PHP", "PHP"),
                    ("Swift", "Swift"),
                    ("Kotlin", "Kotlin"),
                    ("C#", "C#"),
                    ("SQL", "SQL"),
                    ("Data Analysis", "Data Analysis"),
                    ("Machine Learning", "Machine Learning"),
                    ("Artificial Intelligence", "Artificial Intelligence"),
                    ("Data Science", "Data Science"),
                    ("Web Development", "Web Development"),
                    ("Mobile App Development", "Mobile App Development"),
                    ("UI/UX Design", "UI/UX Design"),
                    ("Project Management", "Project Management"),
                    ("Agile/Scrum", "Agile/Scrum"),
                    ("Leadership", "Leadership"),
                    ("Communication Skills", "Communication Skills"),
                    ("Problem-solving", "Problem-solving"),
                    ("Teamwork", "Teamwork"),
                    ("Presentation Skills", "Presentation Skills"),
                    ("Networking", "Networking"),
                    ("Marketing", "Marketing"),
                    ("Sales", "Sales"),
                    ("Finance", "Finance"),
                    ("Accounting", "Accounting"),
                    ("Human Resources", "Human Resources"),
                    ("Digital Marketing", "Digital Marketing"),
                    ("Content Writing", "Content Writing"),
                    ("Graphic Design", "Graphic Design"),
                    ("Video Editing", "Video Editing"),
                    ("Photography", "Photography"),
                    ("Event Planning", "Event Planning"),
                    ("Foreign Languages", "Foreign Languages"),
                    ("Time Management", "Time Management"),
                    ("Customer Service", "Customer Service"),
                    ("Public Speaking", "Public Speaking"),
                    ("Research", "Research"),
                    ("Critical Thinking", "Critical Thinking"),
                    ("Presentation Design", "Presentation Design"),
                    ("Microsoft Office Suite", "Microsoft Office Suite"),
                    ("Google Suite", "Google Suite"),
                    ("Project Coordination", "Project Coordination"),
                    ("Social Media Management", "Social Media Management"),
                    ("Product Management", "Product Management"),
                    ("Quality Assurance", "Quality Assurance"),
                    ("DevOps", "DevOps"),
                    ("Cloud Computing", "Cloud Computing"),
                    ("Network Security", "Network Security"),
                ],
                max_length=30,
            ),
        ),
    ]
