# Generated by Django 4.2 on 2023-04-30 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_interview_delete_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="interview_time",
            field=models.TimeField(default=datetime.time),
        ),
    ]
