# Generated by Django 4.2 on 2023-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_profile_bio_alter_skill_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="student_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Freshman", "Freshman"),
                    ("Sophomore", "Sophomore"),
                    ("Junior", "Junior"),
                    ("Senior", "Senior"),
                    ("Graduate", "Graduate"),
                ],
                max_length=10,
            ),
        ),
    ]
