# Generated by Django 4.2 on 2023-04-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_interview_interview_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="interview_time",
        ),
    ]
