# Generated by Django 4.2 on 2023-04-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_interview_interview_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="interview_date",
            field=models.DateField(),
        ),
    ]
